### ISSUE TITLE
Very confusing write up

### ISSUE THREAD

**Issue by dannyenfp** [learn-co-curriculum/js-advanced-scope-arrow-functions-readme#10]
I have never seen comments in open brackets and what not... I find this lab to be pretty badly written, especially the below portion: 

const square = (n => n * n)[
  // note that while the function is anonymous, we have assigned it to the variable 'square'
 
  (1, 2, 3)
]
  .map(n => n * n)
  [
    // [1, 4, 9]
    // The shorthand nature of arrow functions makes them useful for inline definitions
 
    (1, 2, 3)
  ].map(square);
// [1, 4, 9]

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dannyenfp.

We have updated the materials, fixed these code snippets and added some details for clarity and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
