### ISSUE TITLE
capital N should be small n

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-advanced-scope-arrow-functions-readme#11]
There is a lone capital N in one of the examples, which is a small n everywhere else:
const oldSquare = function(n) {
  return n * N;
};

My suggestion would be to change the capital N to a small n.

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback. We've updated the materials
and fixed this error.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
