### ISSUE TITLE
Both of

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-advanced-scope-arrow-functions-readme#12]
Need "of" after "Both" in this sentence:
"Both the following examples use an arrow function as the callback for map, but notice the different context:"

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe the issue has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
