### ISSUE TITLE
'scope' vs. 'context'

### ISSUE THREAD

**Issue by rrcobb** [learn-co-curriculum/js-advanced-scope-arrow-functions-readme#8]
> If we use an arrow function, the inner function retains the scope of the method it was declared in.

This is true of all functions - they have access to variables local to their containing function. The _context_ is what arrow functions retain that other functions do not.

Should read (something like)

> If we use an arrow function, the inner function retains the context of the method it was declared in.  That way, `this` inside the arrow function will be the same as `this` inside the containing function, the same as if we had called `bind` manually.

This is a pretty confusing concept already, so it's probably worth making sure that we are consistent with terms.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @rrcobb.

We have updated the materials using your suggestion and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
